### ISSUE TITLE
[doctrine/mongodb-odm-bundle] Impossible to set db name via MONGODB_URL

### ISSUE THREAD

**Issue by BoShurik** [symfony/recipes-contrib#75]
MONGODB_URL=mongodb://localhost:27017/symfony
but uses `default` db

**Comment by stof** [comment]
Well, please show us the configuration you have in your project for the doctrine_odm bundle

**Comment by BoShurik** [comment]
Same as in recipe:
```
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: App\Document\
                    alias: App
```
